source 'https://rubygems.org'

#gem 'capybara'
gem "capybara", "~> 2.1.0.rc1"
gem "selenium-webdriver"
gem 'cucumber'
gem 'rspec'
gem 'sinatra'
gem 'headless'
#gem 'selenium'
group :test do
 gem 'rspec-rails'   # library of Rails assertions
 gem 'cucumber-rails', :require => false
 gem 'launchy'
 gem 'database_cleaner'
end
